services:
  db:
    container_name: nest-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  app:
    container_name: nest-app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/src/app
      - /src/app/node_modules
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
    command: yarn start:dev
    restart: always

  pgadmin:
    container_name: nest-pgadmin4
    image: dpage/pgadmin4

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    restart: always
